version: '2'
services:
    web:
        build: .
        depends_on:
            - redis
        env_file: .env
        environment:
            - REDIS_HOST=redis
        ports:
            - "443:3000"
    redis:
        image: redis:3
